### ISSUE TITLE
FAQ nur einspaltig

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#10]
FAQ Detailseite lieber nur 1 großes Feld über die ganze breite mit Fließtext, keine 2 nebeneinander. sowohl im back- als auch im frontend. Falls ich das so gelayoutet habe hau mich.

![image](https://cloud.githubusercontent.com/assets/19430535/16375226/b62fea56-3c5a-11e6-8ef5-666685a39d20.png)

**Comment by kremin** [comment]
fühl Dich gehauen ;) Ändere ich auf einen Ein-Spalter.

**Comment by Matteng123** [comment]
aua!

2016-06-27 12:16 GMT+02:00 Daniel Kremin notifications@github.com:

> fühl Dich gehauen ;) Ändere ich auf einen Ein-Spalter.
> 
> > Am 27.06.2016 um 11:32 schrieb Matteng123 notifications@github.com:
> > 
> > FAQ Detailseite lieber nur 1 großes Feld über die ganze breite mit
> > Fließtext, keine 2 nebeneinander. sowohl im back- als auch im frontend.
> > Falls ich das so gelayoutet habe hau mich.
> > 
> > <
> > https://cloud.githubusercontent.com/assets/19430535/16375226/b62fea56-3c5a-11e6-8ef5-666685a39d20.png
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/Matteng123/iAmbulanz/issues/10>, or mute the thread <
> > https://github.com/notifications/unsubscribe/AAtGAndAcM3NdZdwWc06dG_Wk-fH4405ks5qP5ihgaJpZM4I-6eg
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Matteng123/iAmbulanz/issues/10#issuecomment-228706989,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASh8hy5M2NEWDwilZpxx-uC2NcA28Szsks5qP6LzgaJpZM4I-6eg
> .

## 

 Matteng
WEBDESIGN / UI/UX / KONZEPTE & SO

T: +49 151 27 52 64 89
W: matteng.de
