### ISSUE TITLE
"Springen" der Seite beim Laden

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#11]
sobald ich auf die seite gehe merkt man, daß die schriften geladen werden usw. d.h. sie springt merklich bei jedem reload. ich vermute mal, daß das ne geschwindigkeitssache/optimierung für speedtest usw. ist - frage wäre: geht das noch besser/anders?

das issue hat aber auf keinen fall prio.

**Comment by kremin** [comment]
läßt sich nur per preloader lösen. den hätten wir nur initial einmal. könntest ja einen gestalten, dann setze ich den um.

## 

i.A. Daniel Kremin
Creative Direction Interactive | Dipl. Des.

---

CADMAN
Real Estate Marketing

CADMAN GmbH – Real Estate Marketing
Kaiserswerther Str. 183 a
40474 Düsseldorf

T    +49 (0)211 86752-15
F    +49 (0)211 86752-11
@   kremin@cadman.de mailto:kremin@cadman.de
w    www.cadman.de http://www.cadman.de/

---

Sitz der Gesellschaft: Kaiserswerther Str. 183 , 40474 Düsseldorf
Geschäftsführer: Marc Kömmerling, Dipl.-Kfm. Peter Jücker
Düsseldorf HRB 41966

**Comment by Matteng123** [comment]
lassen wir erstmal so. ist auf absoluter nice-to-have ebene. falls am ende
zeit über ist

Am 27. Juni 2016 um 12:15 schrieb Daniel Kremin notifications@github.com:

> läßt sich nur per preloader lösen. den hätten wir nur initial einmal.
> könntest ja einen gestalten, dann setze ich den um.
> 
> ## 
> 
> i.A. Daniel Kremin
> Creative Direction Interactive | Dipl. Des.
> 
> ---
> 
> CADMAN
> Real Estate Marketing
> 
> CADMAN GmbH – Real Estate Marketing
> Kaiserswerther Str. 183 a
> 40474 Düsseldorf
> 
> T +49 (0)211 86752-15
> F +49 (0)211 86752-11
> @ kremin@cadman.de mailto:kremin@cadman.de
> w www.cadman.de http://www.cadman.de/
> 
> ---
> 
> Sitz der Gesellschaft: Kaiserswerther Str. 183 , 40474 Düsseldorf
> Geschäftsführer: Marc Kömmerling, Dipl.-Kfm. Peter Jücker
> Düsseldorf HRB 41966
> 
> > Am 27.06.2016 um 12:10 schrieb Matteng123 notifications@github.com:
> > 
> > sobald ich auf die seite gehe merkt man, daß die schriften geladen
> > werden usw. d.h. sie springt merklich bei jedem reload. ich vermute mal,
> > daß das ne geschwindigkeitssache/optimierung für speedtest usw. ist - frage
> > wäre: geht das noch besser/anders?
> > 
> > das issue hat aber auf keinen fall prio.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/Matteng123/iAmbulanz/issues/11>, or mute the thread <
> > https://github.com/notifications/unsubscribe/AAtGAqE3X38z12N64Z9Ah12zE6kPLTzdks5qP6GmgaJpZM4I-8et
> > .
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Matteng123/iAmbulanz/issues/11#issuecomment-228706879,
> or mute the thread
> https://github.com/notifications/unsubscribe/ASh8hwxjc1FLHN4t6Lauk-ZoeHO_qIDeks5qP6LTgaJpZM4I-8et
> .

## 

 Matteng
WEBDESIGN / UI/UX / KONZEPTE & SO

T: +49 151 27 52 64 89
W: matteng.de

**Comment by kremin** [comment]
Na geht fix, würde ich aber in der Tat am Ende machen.

**Comment by kremin** [comment]
Sollte ein bißchen besser sein aber der Loader kommt zum Schluss

**Comment by kremin** [comment]
Hat jetzt nen Loader
