### ISSUE TITLE
Wie lege ich die "Anleitungen" bei den Services fest

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#12]
gibt es eine möglichkeit das im backend zu definieren? wir hatten ja gesagt die eigentlichen anleitungen sind feste module, aber wie ich sie auswähle finde ich leider nicht.

![image](https://cloud.githubusercontent.com/assets/19430535/16521708/f4e5ebba-3f98-11e6-9846-6ea9f4598d72.png)

**Comment by kremin** [comment]
Die sind an die Icons gekoppelt und feste Module.
