### ISSUE TITLE
mapbox kartenstyle

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#13]
hatte die schon angelegt, ist evtl. untergegangen:

style-url:
mapbox://styles/iambulanz/cip82lhc30027cunsj60ghzrw

access token:
pk.eyJ1IjoiaWFtYnVsYW56IiwiYSI6ImNpb3Q0YjE5YzAwMjl3OWx3c2w0bmxicmsifQ.xDMAtHedcNDrZ4ZHmvBtlw

**Comment by kremin** [comment]
Brauche einen Download. Du kannst den Style downloaden. Pls.
