### ISSUE TITLE
Neue Icons einpflegen

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#15]
Liegen hier:
Dropbox\Relaunch iAmbulanz\content\icons

habe das handy nochmal neu gemacht - das ist jetzt in der outline etwas dicker. das wäre das einzige, was ersetzt werden müsste:

![image](https://cloud.githubusercontent.com/assets/19430535/16682860/e98c4ac0-44fc-11e6-9d47-7620174d0935.png)

**Comment by kremin** [comment]
Online
