### ISSUE TITLE
Neuer Mapmarker

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#16]
Robert möchte einen anderen Marker haben. Liegt auch unter Icons:

![image](https://cloud.githubusercontent.com/assets/19430535/16682880/061145f6-44fd-11e6-9496-b3fcf621a796.png)

**Comment by kremin** [comment]
Wo unter Icons?

**Comment by kremin** [comment]
Aah Dropbox :)

**Comment by Matteng123** [comment]
yes!  Dropbox\Relaunch iAmbulanz\content\icons

**Comment by kremin** [comment]
Ich brauche den @2 für Retina auch

**Comment by kremin** [comment]
Online
