### ISSUE TITLE
Modul der Schäden wie auf Unternehmensseite bauen

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#18]
ist mir auch total durchgegangen. danke für den hinweis!

![image](https://cloud.githubusercontent.com/assets/19430535/17053772/d629f59c-5003-11e6-9034-0b8ba3ac86d5.png)

**Comment by kremin** [comment]
Ist angelegt. Müssen nur mal sehen wie sich das verhält wenn es nur 3 Produktgruppen gibt.
