### ISSUE TITLE
nice 2 have: abstand teaserrreihen

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#19]
eigentlich waren nur max 4 voreile vorgesehen, aber es sind jetzt doch mehr geworden. ist eigentlich auch gut, daß das geht. frage wäre: kann man das schlau einrichten, daß der abstand der reihen immer nach 4 elementen größer ausfällt? 

![image](https://cloud.githubusercontent.com/assets/19430535/17053826/1e64f960-5004-11e6-8158-d35d5c166e39.png)

**Comment by kremin** [comment]
Ja klar

**Comment by kremin** [comment]
fixed
