### ISSUE TITLE
Slider Sublines zu klein

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#21]
Die Sublines im Slider sind noch um einiges zu klein verglichen mit dem Layout:

Website:
![image](https://cloud.githubusercontent.com/assets/19430535/17056095/6b285064-5011-11e6-84dc-30d6ed41807d.png)

Layout:
![image](https://cloud.githubusercontent.com/assets/19430535/17056107/7a82adc0-5011-11e6-8564-79dcad3f3aed.png)

**Comment by Matteng123** [comment]
Falls ohne größere Umstände möglich - es wäre cool wenn die button auch größer sind. die buttongröße wie unten im footer würder glaueb ich auch gehen.

**Comment by kremin** [comment]
Mit der Buttongröße sind wir einheitlich nur der Footer bricht raus. Ich schau nochmal wegen des Buttons, Subline müsste jetzt passen
