### ISSUE TITLE
Font-Size fliesstext

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#22]
ich glaube wir müssen für desktop nochmal mit dem fliesstext größer werden. ich erwische mich heute ständig dabei, daß ich denke das ist zu klein. liegt aber wohl hauptsächlich an der grotesk. das hattest du ja auch gesagt - die ist schon anders.

habe mal ausprobiert und fänd was in richtung 18px für den fließtext gut. ist hoffentlich nur eine kleine variable ... wenn nicht sag bescheid.

**Comment by kremin** [comment]
Schau mal.
