### ISSUE TITLE
Facebook Bewertungen in den Footer einbauen.

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#23]
Kommt Prio-Mäßig auch eher nach hinten. Hab schon gesucht - scheint gar nicht soooo einfach zu sein. Vorschlag für die Position:

![image](https://cloud.githubusercontent.com/assets/19430535/17061648/dcde1a68-502f-11e6-9dc3-b3da5b7dfaa6.png)

müsstest du aber schauen inwiefern das passt. wenn nicht - sag bescheid.

**Comment by kremin** [comment]
Hast Du das schon mal irgendwo gesehen. In der FB Api steht das die Daten nur nach Login zu sehen sind. DH. der User muss bei FB angemeldet sein. Ich kann das entsprechend abfragen. Ist aber mit Testing ein halber Tag arbeit. Und würde ich als Update verstehen.
