### ISSUE TITLE
Texte für Fragezeichen Kleinkomponente

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#26]
![image](https://cloud.githubusercontent.com/assets/19430535/17062507/7da6db94-5033-11e6-9abf-21c7d90bf129.png)

Zu Kleinkomponenten zählen folgende Teile:

Kamera
Kameralinse
Innenkamera
Hörmuschel
Homebutton
Powerbutton 
Lautstärkeregler
Stummschalter 
Ladebuchse
Lautsprecher
Mikrofon
Kopfhörerbuchse
Backcover / Mittelrahmen
SIM / SD Kartenleser 
WLAN / Bluetooth Antenne

**Comment by kremin** [comment]
Eingefügt
