### ISSUE TITLE
Button Animationen klappen nicht mehr

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#4]
bei mir gehen die mousoever bei den roten großen buttons nicht mehr.

![image](https://cloud.githubusercontent.com/assets/19430535/15923637/7e1977a2-2e2e-11e6-9402-9267b943254b.png)

**Comment by kremin** [comment]
Der letzte Akt gestern für active auf der Preise-Seite hat es dann wohl rausgehauen. 
Fixe ich schnell.

**Comment by kremin** [comment]
Läuft wieder
