### ISSUE TITLE
Schritt 6 - Aufschlüsselung Kosten

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#41]
Kosten werden aufgeführt ohne Leistung nennen. Ist es möglich statt „Analyse & Reparatur“ 
zB „Diagnose & Austausch der Displayeinheit“ aufzuführen?

**Comment by kremin** [comment]
Erklär mir die Logik dahinter, also wo bekomme ich die Texte her? Lass darüber sprechen.

**Comment by Matteng123** [comment]
das sieht gut aus! ich glaube du bist gerade dran, ist aber genauso wie geplant! top!
