### ISSUE TITLE
Telefonnummern klickbar machen

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#43]
Bitte alle Telefonnummern klickbar bzw anrufbar machen

**Comment by kremin** [comment]
Dann werden dass auch Links - richtig?

**Comment by Matteng123** [comment]
ich würde das aussehen beibehalten, aber sie auf dem smartphone wie einen link behanden. ist das in gutem rahmen machbar?

**Comment by kremin** [comment]
Done
