### ISSUE TITLE
icon anleitung bei service klappt nicht mehr

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#44]
nur beim ersten "vor ort" werden in schritt 5 die icons angezeigt. dann leider nicht mehr. habe auch probiert zu ändern oder neues hinzuzufügen. klappt leider nicht.

**Comment by kremin** [comment]
habe das Template angepasst. Sollte jetzt laufen. Bitte prüfen.

**Comment by Matteng123** [comment]
express-service geht leider noch nicht.

**Comment by Matteng123** [comment]
jetzt geht es auch auf der startseite nicht mehr - da ging kurzzeitig alles. etwas seltsam - ggfs hat robert da gleichzeitig geplfegt.

**Comment by kremin** [comment]
Erledigt
