### ISSUE TITLE
Tooltipps in der Karte gehen nur 1x

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#47]
Man kann meistens nur einen Tooltipp einmal aufmachen, danach geht nix mehr (Chrome, firefox - PC)

**Comment by kremin** [comment]
Sollte erledigt sein. Bitte prüfen.

**Comment by Matteng123** [comment]
immer, nachdem ich düsseldorf aufgemacht habe gehts nicht mehr. Getestet in FF und chrome

**Comment by kremin** [comment]
Hab noch einen Case gefunden der das breakt. Jetzt geht es
