### ISSUE TITLE
Preis bei Service einfügen

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#48]
mist. voll vergessen den preis beim service einzufügen. du weisst als user nicht was es kostet wenn du den service nimmst. daher wäre es super den noch in der headline einzubauen. "Express-Service | 30 - 60 Minuten | + XX €"

**Comment by kremin** [comment]
Mache ich aber das problem ist, dass der Preis für die Berechnung trotzdem hart im Template steht. Also wenn er die Preise ändert muss er uns bescheid geben. Oder ich muss die Logik da nochmal umbauen und mir die Preise aus den Services ziehen.

**Comment by kremin** [comment]
Ha, gelogen. Sehe gerade, dass ich das schon gemacht habe :) Der Preis kommt aus dem Kirby, hach manchmal bin ich schon ein Fuchs. es fehlte nur die Ausgabe im Template :)

**Comment by kremin** [comment]
Erledigt
