### ISSUE TITLE
IE11 / PC Keine Karte bei Standorte

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#49]
hat robert noch nicht gesehen, aber ist mir aufgefallen, da geht die karte gar nicht. im edge geht sie. Angeblich auch im Chrome, aber ich weiß nicht welches betriebssystem.

**Comment by kremin** [comment]
Es braucht webgl. Hat der 11er aber. G

**Comment by kremin** [comment]
Hab da gerade mal ein Update gemacht, das muss fix auf den Live server
