### ISSUE TITLE
Bei Landingpages werden keine Inhalte dargestellt

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#5]
ich vermute, daß es einfach noch nicht eingerichtet ist, aber ich kann noch keine Inhalte in die Landingpage einstellen. es sieht immer so aus: 

![image](https://cloud.githubusercontent.com/assets/19430535/15923722/dcac003c-2e2e-11e6-8516-d86bfac38566.png)

**Comment by kremin** [comment]
Si. Haben wir Inhalte?

**Comment by Matteng123** [comment]
Hab mal testweise was reingehauen, aber die Seite sieht immer noch wie auf dem Screenshot aus. Scheint das irgendwie nicht da reinzupushen.

**Comment by kremin** [comment]
Hat sich das geklärt?

**Comment by Matteng123** [comment]
ja, hat sich geklärt!
