### ISSUE TITLE
Kleinkomponenten geben keinen preis mehr aus

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#50]
kann auch ein pflegefehler sein - jedenfalls bekomme ich keine preise mehr angezeigt obwohl sie eigentlich drin sind "preis nicht ermittelbar" sobald ich kleinkomponente anwähle. kann das an dem slash "/" z.b. bei "bluetooth / WLAN" liegen?

**Comment by Matteng123** [comment]
habs gerade nochmal getestet. auch wenn ich die ensprechenden einträge bei kleinkomponente mit / herausnehme kommt immer ein "preis nicht ermittelbar" heraus.

**Comment by kremin** [comment]
Schaue.

**Comment by kremin** [comment]
Done
