### ISSUE TITLE
Backcover/Mittelrahmen als Begriff entfernen

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#52]
Hilfetexte aus Fragezeichen-Bubble und Button-Mouseover im Tool wie folgt modifizieren:
Backcover/Mittelrahmen entfernen

![image](https://cloud.githubusercontent.com/assets/19430535/17857700/0ceb80fe-6883-11e6-8040-8ea505d5fa22.png)

**Comment by kremin** [comment]
Done
