### ISSUE TITLE
Geräteabhängige Zeitangabe

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#56]
Das Feld zur Zeit soll ein freies Kirby Textfeld werden. Die Angabe soll je Hersteller gemacht werden können.

![image](https://cloud.githubusercontent.com/assets/19430535/19936754/fbdbf03a-a11e-11e6-9680-82ea63432d2c.png)

Die Zeiteinschätzungen in den Services sollen dafür überall raus:
![image](https://cloud.githubusercontent.com/assets/19430535/19936851/5bd95cac-a11f-11e6-8963-7a3d790d8106.png)

**Comment by kremin** [comment]
Die Zeiteinschätzung bei den Services ist redaktionell eleminierbar. Ich kann es aber auch bei den Kirbfelder rausnehmen. Das ist wahrscheinlich sauberer. 

Aufwand: 
- Ergänzung Servicezeit je Device nicht je Hersteller
  -- Blueprint erweiterung, Funktion zur Ermittlung der Servicesite anhand des gewählten Devices, Ausgabe im Template, Testlauf auf Testserver, Abstimmung, Übertragen der Daten auf Liveserver, Eintragen eines Standardwertes: 0.5 Tage
- Entfernen der Servicezeiten in der Serviceaufstellung:
  -- Blueprint reduktion, Template anpassen, Daten aus .txt Dateien entfernen, Testlauf auf Testserver, Übertragen der Daten auf Liveserver, entfernen der Werte aus txt-Dateien auf Liveserver: 2std

**Comment by kremin** [comment]
Hier muss Robert dann fix die Zeit für die Geräte pflegen. Sag bescheid wenn ich damit online gehen darf.
