### ISSUE TITLE
PDF Download bei "Postversand" klappt nicht

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#58]
Der Download-button im letzten schritt geht nicht.

![image](https://cloud.githubusercontent.com/assets/19430535/20385395/88ece62a-acb7-11e6-81fa-b700783d3a1c.png)

**Comment by kremin** [comment]
Ist ein PDF gepflegt?

**Comment by kremin** [comment]
Ist im Update mit drin.

**Comment by Matteng123** [comment]
das hier hatte er auch nochmal angefragt. mit dem update ist das letzte update gemeint, oder? kann das zeitlich nicht mehr ganz nachvollziehen. wäre top!

**Comment by kremin** [comment]
Das ist in dem update drin das wir einspielen müssen.
