### ISSUE TITLE
Die Geräte werde noch nicht dargestellt

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#6]
Wahrscheinlich einfach noch nicht eingerichtet. Hier fehlen noch die Buttons für die Geräte:

![image](https://cloud.githubusercontent.com/assets/19430535/15923939/f19e5cd2-2e2f-11e6-9b60-4c2e169b3aec.png)

**Comment by kremin** [comment]
Da sind in der Tat noch keine Inhalte hinterlegt, bei den Landingpages.

**Comment by kremin** [comment]
Geräte werden jetzt auch hier ausgegeben.
