### ISSUE TITLE
menü "bounct" sehr krass beim öffnen.

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#8]
auf meinem iphone springt das menü ganz nervös auf und ab wenn ich es öffne und schliesse. ggfs. zuviel bounce drin. hab n iphone 6s. getestet mit chrome und safari.

**Comment by kremin** [comment]
da hoppelt in der tat einiges. im simulator ist alles fein. ich denke das das sticky menu da querfunkt. fixe ich.

**Comment by kremin** [comment]
ist gefixt
