### ISSUE TITLE
Slider geht erst ab 2 Bildern

### ISSUE THREAD

**Issue by Matteng123** [Matteng123/iAmbulanz#9]
Slider taucht erst ab 2 Slides auf, d.h. ich kann keinen "einfachen" header damit erstellen. ist mir bei http://iambulanz.matteng.de/meta-about aufgefallen

**Comment by kremin** [comment]
Damn, ja das stimmt. Der Slider kann nur mehrere Bilder. Da muss ich einen Fallback machen.

**Comment by kremin** [comment]
Ist gefixt
